name: 'Clean Up Workspace'
description: 'Remove all files from GitHub Actions runner workspace'
branding:
  icon: 'trash'
  color: 'green'
runs:
  using: 'composite'
  steps:
    - name: Clean Workspace
      run: |
        df -h
        ls -la
        sudo rm -rf ./.* ./* || true
        df -h
        ls -la
      shell: bash
